services:
  app:
    build:
      dockerfile: Dockerfile
      target: prod
    healthcheck:
      test: []
      disable: true
    networks:
      default: {}

  db:
    ports: !reset []
    networks:
      default: {}

networks:
  default: {}
