services:
  app: &base
    build:
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env.dist
    volumes:
      - ./:/usr/src/app
    ports:
      - "4321:4321"
    depends_on:
      db:
        condition: service_healthy

  cron:
    <<: *base
    command: ['crond', '-f']
    ports: []
    healthcheck:
      test: []
      disable: true

  db:
    image: postgres:15-alpine
    env_file:
      - .env.dist
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s